/**
 * KiMedia Dashboard — shared type contract.
 *
 * These types mirror:
 *   • D1 tables  (schema.sql)
 *   • IngestPayload sent by kiboy/publisher.py via POST /api/ingest
 *
 * IMPORTANT: any change here must be reflected in schema.sql AND publisher.py.
 */

// ─────────────────────────────────────────────
// Categories (1-5, fixed mapping)
// ─────────────────────────────────────────────

export const CATEGORIES = {
  1: { key: 'model_research',    label: 'Model & Research',     emoji: '🧠' },
  2: { key: 'industry_business', label: 'Industry & Business',  emoji: '💰' },
  3: { key: 'regulasi_etika',    label: 'Regulasi & Etika',     emoji: '⚖️' },
  4: { key: 'robotics_hardware', label: 'Robotics & Hardware',  emoji: '🤖' },
  5: { key: 'creative_media',    label: 'Creative & Media',     emoji: '🎬' },
} as const;

export type CategorySeq = keyof typeof CATEGORIES;

export type Category = {
  key: string;
  label: string;
  emoji: string;
};

// ─────────────────────────────────────────────
// Platform variants (generated by Kiboy LLM)
// ─────────────────────────────────────────────

/** One post in a thread (Threads / Twitter multi-post). */
export type PlatformPost = {
  index: number;       // 1 = main post, 2 = source reply
  text: string;
  char_count: number;  // MUST be <= platform limit
  has_image: boolean;
};

/** Threads: max 490 chars per post (including title). 2 posts. */
export type ThreadsVariant = {
  posts: [PlatformPost, PlatformPost];  // post[0] = content, post[1] = source
  total_chars: number;
};

/** Instagram: max 2000 chars caption. 1 image. */
export type InstagramVariant = {
  caption: string;
  char_count: number;  // MUST be <= 2000
  hashtags: string[];
  has_image: boolean;
};

/** Twitter/X: max 260 chars per post. 2 posts. */
export type TwitterVariant = {
  posts: [PlatformPost, PlatformPost];  // post[0] = hook, post[1] = source
  post_count: number;
};

export type PlatformVariants = {
  threads:   ThreadsVariant;
  instagram: InstagramVariant;
  twitter:   TwitterVariant;
};

// ─────────────────────────────────────────────
// Ingest payload — sent by kiboy/publisher.py
// This is the contract between Python and the /api/ingest endpoint.
// ─────────────────────────────────────────────

export type IngestPayload = {
  /** Unique article ID: "<YYYY-MM-DD>_<HH.MM>-<NN>" */
  id: string;

  // Temporal
  date: string;   // "2026-06-07"
  time: string;   // "16.44"
  seq: 1 | 2 | 3 | 4 | 5;

  // Content
  title_short: string;   // from "# NN — emoji <this part>"
  title_id: string;      // full Indonesian title from "## <this>"
  body_md: string;       // article body (markdown)
  thumb_headline: string; // with optional **accent** markup

  // Source (MUST be real URL, never GN redirect)
  source_domain: string;
  source_name: string;
  source_url: string;

  // Images
  image_original: string | null;  // OG image URL from original article
  thumbnail_png_b64: string;      // Base64-encoded 1080x1350 PNG thumbnail

  // Platform variants (generated by Kiboy LLM)
  variants: PlatformVariants;

  /** ISO timestamp (WIB) when publisher ran */
  generated_at: string;
};

// ─────────────────────────────────────────────
// Article — as stored in D1 and returned by API
// ─────────────────────────────────────────────

export type Article = {
  id: string;
  date: string;
  time: string;
  seq: number;
  category: Category;
  title_short: string;
  title_id: string;
  body_md: string;
  thumb_headline: string | null;
  source_domain: string | null;
  source_name: string | null;
  source_url: string;
  image_original: string | null;
  thumbnail_r2_url: string | null;  // public R2 URL (null until uploaded)
  has_real_image: boolean;
  variants: PlatformVariants;
  generated_at: string;
  created_at: string;
  // Joined from post_status:
  status?: ArticleStatus;
};

/** Lightweight version for dashboard grid (no body, no variants). */
export type ArticleListItem = {
  id: string;
  date: string;
  time: string;
  seq: number;
  category: Category;
  title_short: string;
  thumbnail_r2_url: string | null;
  has_real_image: boolean;
  generated_at: string;
  status?: ArticleStatus;
};

// ─────────────────────────────────────────────
// Post status
// ─────────────────────────────────────────────

export type Platform = 'threads' | 'instagram' | 'twitter';
export type PostStatusValue = 'pending' | 'posted' | 'skipped';

export type PostStatusEntry = {
  article_id: string;
  platform: Platform;
  status: PostStatusValue;
  posted_at: string | null;
  posted_by: string | null;
  note: string | null;
  updated_at: string;
};

/** Aggregated status for all 3 platforms for one article. */
export type ArticleStatus = Record<Platform, PostStatusValue>;

export const DEFAULT_STATUS: ArticleStatus = {
  threads:   'pending',
  instagram: 'pending',
  twitter:   'pending',
};

// ─────────────────────────────────────────────
// API response shapes
// ─────────────────────────────────────────────

export type ApiSuccess<T> = { ok: true;  data: T };
export type ApiError      = { ok: false; error: string; code?: number };
export type ApiResponse<T> = ApiSuccess<T> | ApiError;
