#!/usr/bin/env python3
"""Filter candidates: keep only real AI news from recognized sources, not Google News noise."""
import json, re

with open('candidates.json') as f:
    candidates = json.load(f)

# Recognized quality sources (not aggregators/stock advice/etc)
QUALITY_DOMAINS = {
    'techcrunch.com', 'arstechnica.com', 'theverge.com', 'www.theverge.com',
    'www.techcrunch.com', 'www.arstechnica.com',
    'wired.com', 'www.wired.com',
    'cnbc.com', 'www.cnbc.com',
    'bloomberg.com', 'www.bloomberg.com',
    'reuters.com', 'www.reuters.com',
    'apnews.com', 'www.apnews.com',
    'bbc.com', 'www.bbc.com', 'bbc.co.uk', 'www.bbc.co.uk',
    'nytimes.com', 'www.nytimes.com',
    'wsj.com', 'www.wsj.com',
    'fortune.com', 'www.fortune.com',
    'forbes.com', 'www.forbes.com',
    'businessinsider.com', 'www.businessinsider.com',
    'engadget.com', 'www.engadget.com',
    'venturebeat.com', 'www.venturebeat.com',
    'theinformation.com', 'www.theinformation.com',
    'theguardian.com', 'www.theguardian.com',
    'npr.org', 'www.npr.org',
    'politico.com', 'www.politico.com',
    'axios.com', 'www.axios.com',
    'thehill.com', 'www.thehill.com',
    'nbcnews.com', 'www.nbcnews.com',
    'cbsnews.com', 'www.cbsnews.com',
    'abcnews.go.com',
    'latimes.com', 'www.latimes.com',
    'hollywoodreporter.com', 'www.hollywoodreporter.com',
    'variety.com', 'www.variety.com',
    'deadline.com', 'www.deadline.com',
    'rollingstone.com', 'www.rollingstone.com',
    'indiewire.com', 'www.indiewire.com',
    'theatlantic.com', 'www.theatlantic.com',
    'newyorker.com', 'www.newyorker.com',
    'scientificamerican.com', 'www.scientificamerican.com',
    'nature.com', 'www.nature.com',
    'science.org', 'www.science.org',
    'nikkei.com', 'www.nikkei.com', 'asia.nikkei.com',
    'scmp.com', 'www.scmp.com',
    'ft.com', 'www.ft.com',
    'economist.com', 'www.economist.com',
    'blog.google', 'blog.google',
    'anthropic.com', 'www.anthropic.com',
    'openai.com', 'www.openai.com', 'openai.com/blog',
    'meta.com', 'about.fb.com', 'about.meta.com',
    '9to5mac.com', '9to5google.com',
    'mashable.com', 'www.mashable.com',
    'gizmodo.com', 'www.gizmodo.com',
    'tomshardware.com', 'www.tomshardware.com',
    'anandtech.com', 'www.anandtech.com',
    'theregister.com', 'www.theregister.com',
    'zdnet.com', 'www.zdnet.com',
    'cnet.com', 'www.cnet.com',
    'techradar.com', 'www.techradar.com',
    'digitaltrends.com', 'www.digitaltrends.com',
    'pcmag.com', 'www.pcmag.com',
    'interestingengineering.com', 'www.interestingengineering.com',
    'livescience.com', 'www.livescience.com',
    'newatlas.com', 'www.newatlas.com',
    'ieee.org', 'spectrum.ieee.org',
    'androidpolice.com', 'www.androidpolice.com',
    'theverge.com', 'www.theverge.com',
    'engadget.com', 'www.engadget.com',
    'techcrunch.com', 'www.techcrunch.com',
    'autoblog.com', 'www.autoblog.com',
    'electrek.co', 'www.electrek.co',
    'teslarati.com', 'www.teslarati.com',
    'insideevs.com', 'www.insideevs.com',
    'foxnews.com', 'www.foxnews.com',
    'bleepingcomputer.com', 'www.bleepingcomputer.com',
    'krebsonsecurity.com', 'krebsonsecurity.com',
    'washingtonpost.com', 'www.washingtonpost.com',
    'usatoday.com', 'www.usatoday.com',
    'time.com', 'www.time.com',
    'newsweek.com', 'www.newsweek.com',
    'popularmechanics.com', 'www.popularmechanics.com',
    'fastcompany.com', 'www.fastcompany.com',
    'inc.com', 'www.inc.com',
    'qz.com', 'www.qz.com',
    'yonhapnews.com', 'www.yonhapnews.com',
    'koreaherald.com', 'www.koreaherald.com',
    'techtimes.com', 'www.techtimes.com',
    'theregister.com', 'www.theregister.com',
    'marketwatch.com', 'www.marketwatch.com',
    'investors.com', 'www.investors.com',
    'blog.google', 'developers.googleblog.com',
    'cloud.google.com/blog',
    'ai.googleblog.com',
    'research.google/blog',
    'openai.com/blog',
    'anthropic.com/news',
    'meta.com/blog',
    'about.fb.com/news',
    'blogs.nvidia.com',
    'nvidianews.nvidia.com',
    'aws.amazon.com/blogs',
    'azure.microsoft.com/blog',
    'cloudflare.com/blog',
    'www.cloudflare.com/blog',
}

# Title blacklist - these are not real AI news
BLACKLIST_PATTERNS = [
    r'horoscope', r'weekly horoscope', r'daily horoscope',
    r'obituary', r'passed away', r'dies at', r'died at',
    r'stock to buy', r'stocks to buy', r'best.*stock', r'1.*stock',
    r'buy.*stock', r'investment.*stock', r'stock.*pick',
    r'artificial intelligence.*stock', r'ai.*stock.*buy',
    r'motley fool', r'fool\.com',
    r'you can buy', r'buy them',
    r'this is my best', r'if i could only buy',
    r'prediction: this', r'prediction.*ai',
    r'crushed nvidia', r'soar higher', r'soar after',
    r'surging', r'surge', r'down \d+%',
    r'gains of.*%', r'gains of.*percent',
    r'join.*trillion club', r'trillion club',
    r'what.*artificial intelligence',
    r'intro to artificial intelligence',
    r'artificial intelligence.*explained',
    r'understanding artificial intelligence',
    r'using artificial intelligence for',
    r'how.*ai.*is.*changing',
    r'hurricane.*artificial intelligence',
    r'pizza', r'recipe', r'cooking',
    r'best.*games', r'sports.*games',
    r'spacecamp', r'space camp',
    r'vaccine', r'coal ash', r'ebola',
    r'kenyan court', r'botnet.*devices',
    r'measles', r'house of the dragon',
    r'fcc warns', r'doj sues', r'ice.*license',
    r'f1 reliability', r'sea cucumber',
    r'rocket report', r'blue origin', r'new glenn',
    r'audi.*drive', r'audi rs5',
    r'god of war', r'tv series',
    r'fantasy football', r'nfl',
    r'claude le mieux', r'claude le mieux',
    r'lemieux', r'nhl', r'canadiens',
    r'hurricanes.*nhl',
    r'gemini horoscope', r'gemini daily',
    r'weekly prediction', r'astrology',
    r'stock analysis', r'technical analysis',
    r'swing trade', r'day trading',
    r'dividend', r'yield',
    r'401k', r'retirement',
    r'credit card', r'mortgage',
    r'insurance',
    r'earnings call', r'earnings report',
    r'q1.*earnings', r'q2.*earnings', r'q3.*earnings', r'q4.*earnings',
    r'fiscal.*quarter',
    r'options trading',
    r'crypto prediction', r'bitcoin price',
    r'register for', r'ticket', r'apply to speak',
    r'last day.*apply', r'final.*hours.*save',
    r'spacecamp', r'40th anniversary',
    r'grifter', r'cynic',
    r'trump.*coal', r'trump.*funding',
    r'campus protests',
    r'too.*ai.*pilled',
    r'what happens when companies',
    r'small business tech news',
    r'populist revolt',
    r'billionaire.*coding genius',
    r'michael burry',
    r'winklevoss',
    r'sports.*game.*of all time',
    r'nba', 'nfl draft', 'super bowl',
    r'crypto exchange', r'crypto firm',
    r'cftc.*gemini', r'cftc.*crypto',
    r'winklevoss', r'bitcoin',
    r'coinbase', r'binance',
    r'peptide antibiotic',
    r'child exploitation',
    r'norman.*schools',
    r'kingsport.*ai',
    r'preserving humanity',
    r'editorial.*ai revolution',
    r'teachers call for',
    r'shared humanity',
    r'first ai high school',
    r'pope reminds',
    r'irish priest',
    r'catholics.*consumers',
    r'guest opinion.*ai',
    r'commentary.*ai.*improving',
    r'taming artificial intelligence',
    r'battle.*regulate.*ai.*dc',
    r'so you.*heard.*ai terms',
    r'discussion.*religion.*ai',
    r'wiu.*artificial intelligence',
    r'gov.*moore.*ai.*lab',
    r'human person.*age.*ai',
    r'what must not be lost',
    r'benedict evans.*ai.*trajectory',
    r'great valley.*mba.*ai',
    r'ai.*clinical.*decision',
    r'tech class.*older adults',
    r'beyond books.*opt out',
    r'human stupidity.*ai',
    r'doe explains.*ai',
    r'alabama.*ai.*legislation',
    r'expert.*tell.*alabama',
    r'artificial intelligence.*market',
    r'artificial intelligence.*energy.*market',
    r'artificial intelligence.*clinical',
    r'so.*ai.*better',
    r'is microsoft.*push',
    r'numbers don\'t lie.*anthropic',
    r'ai model confidence trap',
    r'cardiac amyloidosis',
    r'how to tell if google chrome',
    r'how to automate ai model',
    r'new ai model finds.*cheaper',
    r'the ai trade just broke',
    r'mystery company accidentally blew',
    r'bubble debate',
    r'ai didn\'t kill.*junior developer',
    r'using ai for just minutes',
    r'internet.*ai governance.*internet governance',
    r'nvidia.*plowed.*billion.*ai stocks',
    r'how america can remain',
    r'public health.*data analytics.*ai',
    r'uk cyberspying.*unstoppable force',
    r'leo shows.*planet.*pope.*ai',
    r'data center debates.*arkansas',
    r'india.*ai revolution.*billion.*investments',
    r'ai.*court.*dockets.*lawsuits',
    r'student.*protest.*ai.*pitt',
    r'ai made my expertise more effective',
    r'premium ai features in photoshop',
    r'future.*ai.*still.*questions',
    r'just how ubiquitous.*ai',
    r'spotify.*ai.*remix',
    r'code refresh.*opponent.*ai.*ad',
    r'ai.*sex.*vatican',
    r'plenty.*jobs.*ai',
    r'capital region.*using ai',
    r'virtual assistant.*capital region',
    r'can llms generate enterprise.*code',
    r'teachers union.*pleads.*ai',
    r'enterprise.*too.*ai-pilled',
    r'companies rethink ai spending',
    r'firms spent heavily.*ai.*costs.*value',
    r'anthropic.*tops.*openai.*valuable.*start-up',
    r'anthropic.*now.*worth.*more.*openai',
    r'anthropic.*rockets.*valuation.*topping',
    r'anthropic.*leapfrog.*openai.*valuation',
    r'anthropic.*surpasses.*openai.*valuation',
    r'anthropic.*overtakes.*openai',
    r'why.*anthropic.*become.*more.*valuable',
    r'anthropic.*raises.*billion',
    r'anthropic.*just.*eclipsed.*openai',
    r'anthropic.*just.*topped.*openai',
    r'anthropic.*hits.*valuation.*overtaking',
    r'did anthropic.*checkmate.*openai',
    r'openai.*prepare.*file.*ipo.*weeks',
    r'openai.*confidentially.*file.*ipo',
    r'openai is preparing to file.*ipo',
    r'sky-high.*ipo.*pricing.*people',
    r'openai.*revenue.*chief.*barnstorming',
    r'$39 million.*csus.*renew.*openai',
    r'california state university.*openai.*disaster',
    r'openai.*economist.*vatican.*ai problem',
    r'openai.*discussed adding.*citigroup.*jpmorgan',
    r'openai.*frontier governance framework',
    r'election information.*safeguards.*openai',
    r'parents.*openai.*whistleblower.*suchir balaji',
    r'small business tech news.*uber.*starbucks.*openai',
    r'musk emails.*antitrust.*openai.*apple',
    r'openai.*cost-per-action.*ads.*chatgpt',
    r'openai.*hiring.*robotics',
    r'servicenow.*cmo.*openai',
    r'openai.*anthropic.*ceo.*walk.*job.*warning.*ipo',
    r'openai.*deployment company',
    r'openai.*malta.*chatgpt.*citizen',
    r'openai named leader.*coding agent.*gartner',
    r'shared playbook.*third party.*evaluation',
    r'supercomputer networking.*openai',
    r'next phase.*openai.*education',
    r'new ways.*buy.*chatgpt ads',
    r'csub.*partner.*openai.*program',
    r'how openai delivers.*low-latency.*voice',
    r'openai flexes.*enterprise.*ambitions',
    r'openai docuseries.*indycar.*ganassi',
    r'marketers on the move.*openai',
    r'everything.*know.*openai.*iphone.*rival',
    r'openai.*azerbaijan.*learning.*platform',
    r'introducing openai for singapore',
    r'rs 28 crore.*luxury.*home.*openai.*anthropic',
    r'both anthropic.*openai.*multi-trillion',
    r'spacex.*openai.*windfall.*bets.*asian.*ai.*winner',
    r'how enterprises.*scaling.*openai',
    r'ministry.*science.*openai.*adaptive learning',
    r'my guide to.*ipos.*spacex.*openai.*anthropic',
    r'famous math problem.*ai.*cracked',
    r'anthropic releases claude opus 4.8 surpasses',
    r'apple.*google.*ai researcher.*feedback loop',
    r'introducing claude opus 4.8.*anthropic',
    r'claude opus 4.8.*now available on aws',
    r'anthropic debuts flagship claude opus 4.8',
    r'anthropic confirms claude mythos',
    r'teaching claude why.*anthropic',
    r'pwc.*deploying claude.*anthropic',
    r'kpmg.*integrates claude.*anthropic',
    r'announcing claude managed agents.*cloudflare',
    r'eu seeks.*intensify.*talks.*us.*cyber.*ai.*mythos',
    r'uk banks.*lack.*access.*mythos.*ai.*model',
    r'anthropic plans wide release.*mythos',
    r'researchers put ai models.*simulated society.*grok.*crime',
    r'pope approves.*interdicasterial commission.*ai',
    r'artificial intelligence must be disarmed',
    r'opinion.*pope leo.*humanity',
    r'opinion.*future.*ai.*our own hands',
    r'america can remain.*ai superpower',
    r'powerful ai super pac.*midterm.*war',
    r'eu.*ai.*regulation.*opinion',
    r'pitchforks.*billionaires.*populist.*revolt',
    r'trump regulator.*drop case.*winklevoss',
    r'cfwc.*asks judge.*biden-era.*settlement.*winklevoss',
    r'cfwc.*undo.*gemini penalty',
    r'gemini taps spacexai',
    r'project gemini.*disney.*hulu',
    r'media tek.*dimensity.*gemini nano',
    r'gemini omni.*new family.*ai models',
    r'gemini 3.5 flash.*fast.*gen ai',
    r'i tried turning chatgpt into gemini',
    r'gemini spark.*rolling out.*trust.*ai.*apps',
    r'i gave gemini spark access.*life',
    r'gemini.*hits.*million users',
    r'google.*gemini.*ai avatar tool',
    r'10 ai prompting tips',
    r'catch up.*major io.*moments',
    r'new generation.*ads.*ai.*search',
    r'new era.*ai search',
    r'intelligent eyewear.*coming.*fall',
    r'building.*agentic.*future.*io',
    r'i switched from outlook.*gmail.*gemini',
    r'gemini.*horoscope',
    r'weekly horoscope gemini',
    r'gemini.*weekly horoscope',
    r'gemini monthly predictions',
    r'your daily horoscope',
    r'ramon perio.*gemini era',
    r'iphone user.*switches.*gemini.*android auto',
    r'gemini adds grok-powered research',
    r'gemini crypto exchange launches.*grok',
    r'access chatgpt.*claude.*gemini.*one app',
    r'ai prompt.*tips.*chatgpt.*claude.*gemini',
    r'i asked gemini.*claude.*chatgpt.*debug',
    r'i used gemini and claude.*recipe',
    r'claude.*obituary', r'claude.*obituaries',
    r'claude.*passed away', r'claude.*dies',
    r'claude.*death', r'claude.*hanged',
    r'for claude.*written.*voiced',
    r'claude.*family donates brain',
    r'claude.*brain.*donated.*cte',
    r'claude.*brain.*study',
    r'claude.*cause of death',
    r'claude.*family.*announce.*brain',
    r'canadiens legend claude',
    r'i gave up notebooklm for claude',
    r'remembering claude le mieux',
    r'claude le mieux brain.*boston university',
    r'claude le mieux.*client.*emotional',
    r'mark kiszla.*claude le mieux',
    r'rclaude skill.*productivity hack',
    r'4 claude code settings',
    r'i use claude code and codex',
    r'i stopped using claude for coding',
    r'i ignored this claude feature',
    r'claude ai says you should buy',
    r'chinese firms exploited.*accounts.*extract.*claude',
    r'claude ai makes bullish case',
    r'until may.*get claude',
    r'access chatgpt.*claude.*chatgpt',
    r'teaching claude why',
    r'claude opus 4.8 now available',
    r'conversational.*ai.*feedback',
    r'apple.*google.*ex.*ai.*researchers',
    r'glean.*top-line.*crosses.*million',
    r'glean.*secures.*million',
    r'cloudflare.*ai.*training.*data.*startup',
    r'robot training startup.*clean',
    r'coders.*refusing.*without.*ai.*bite',
    r'asana.*acquires.*stack.*ai',
    r'fed up.*vibe coders.*prompt injection',
    r'the internet.*being rebuilt.*machines',
    r'llms believe false statements',
    r'after nvidia.*billion.*not.*acqui-hire.*groq.*raising',
    r'meta acquires.*assured.*robotics',
    r'mistral.*arthur mensch.*design.*chips',
    r'google.*gemini spark.*agent.*hands-on',
    r'amazon.*future.*data centers.*technical problem',
    r'cnn.*latest.*media.*sue.*perplexity',
    r'vertu.*alphafold.*folding.*phone.*hermes',
    r'paramount.*ai.*ugliest.*star trek.*thumbnail',
    r'cognition.*scott wu.*ai coding agents.*replace.*human',
    r'just like gold.*oil.*trade.*ai token futures',
    r'anthropic.*lease.*spacex.*opinions vary',
    r'humanoid robots strut.*trade show.*japan',
    r'openai.*codex.*control.*windows',
    r'microsoft.*working.*super app',
    r'openai.*canvas',
    r'grok.*get.*windows.*app',
    r'microsoft.*copilot health.*healthcare',
    r'anthropic.*claude.*cowork.*desktop.*agent',
    r'x.*grok.*cracks,*ai image generation',
    r'anthropic.*reportedly.*google.*billion.*chips',
    r'pope.*encyclical.*ai.*dignity',
    r'opportunity.*humanoid.*robots.*evs.*china',
    r'ukraine.*ai.*startup.*drone.*russia',
    r'anthropic.*acquired.*rockset',
    r'openai.*luncurkan.*rosalind.*biodefense',
    r'softbank.*siapkan.*ipo.*roze',
    r'us takes step.*halt.*nvidia.*chip.*shipments.*china',
    r'michigan.*ai.*workforce.*training.*program',
    r'connecticut.*sb5.*regulasi',
    r'connecticut.*tanda tangan.*undang.*ai',
    r'maryland.*ai.*innovation.*lab.*governor',
    r'ilinois.*ai.*safety.*law.*expansive.*mandates',
    r'mount sinai.*ai.*food',
    r'nvidia.*ai.*satellite.*dea',
    r'ohio.*suspends.*data.*center.*tax.*break.*ai',
    r'company.*one.*word.*ai.*stock',
    r'playwright.*ai.*testing',
    r'nvidia.*research.*robotics.*simulation.*real',
    r'nvidia.*launches.*ising.*world.*open.*quantum',
    r'nc.*ai.*posco.*dx.*hand.*robot.*model',
    r'galaxy.*corporation.*humanoid.*robot.*fashion.*seoul',
    r'google.*coscientist.*nature.*hypothesis.*agents.*lab',
    r'researchers.*automated.*llm.*reasoning.*strategy.*cut.*token.*usage',
    r'china post.*humanoid.*robot.*sort.*parcels',
    r'engineai.*129000.*factory.*humanoid.*every.*mins',
    r'hyundai.*atlas.*humanoid.*robot.*football',
    r'netflix.*wiz.*creates.*app.*slash.*bills',
    r'openai.*announces.*gpt.*latest.*ai.*model',
    r'chinas.*deepseek.*releases.*preview.*model',
    r'trump.*admin.*moves.*oversight.*test.*google.*microsoft.*xai.*models',
    r'spotify.*ai.*remix.*era',
    r'spotify.*ai.*music.*slop',
    r'spotify.*boss.*defends.*ai.*music.*better.*slop',
    r'humanoid.*robot.*fashion.*seoul.*cowboy',
    r'pinterest.*ai.*cost.*cutting',
    r'football.*robot.*humanoid',
    r'x.*grok.*windows.*app',
    r'openai.*super.*app.*gabung.*chatgpt.*codex',
    r'microsoft.*copilot.*health.*announced',
    r'samsung.*kirim.*sampel.*chip.*memori.*ai.*hbm',
    r'nvidia.*blackwell.*samsung.*hbm.*deal',
    r'meta.*ngejar.*mimpi.*ai.*jurus.*andalan',
    r'openai.*gpt55.*rls.*model',
    r'deepseek.*v4.*model.*preview.*rlss',
    r'warfare.*here.*cbs.*news.*military.*training.*ai',
    r'us military.*expands.*use.*ai.*safeguards',
    r'pentagon.*artificial.*intelligence.*battlefield',
    r'defense.*ai.*military.*leaders.*caution',
    r'elon.*musk.*bet.*china.*ai.*race',
    r'china.*ai.*pandas.*ev.*robotics',
    r'company.*accidentally.*blew.*million.*claude.*single.*month',
    r'marvel.*ai.*superhero.*creator.*row',
    r'david.*lynch.*ai.*kids.*movie',
    r'paramount.*ai.*star.*trek.*thumbnail',
    r'amazon.*ai.*animated.*good.*advice.*cupcake.*creator.*furious',
    r'softbank.*pledges.*75bn.*europe.*biggest.*ai.*facility.*france',
    r'ai.*dangers.*eclipse.*nuclear.*weapons.*singapore.*forum',
    r'emily.*blunt.*ai.*terrified.*refused.*disclosure',
    r'taylor.*swift.*blind.*spot.*ai.*law.*copyright',
    r'parkinson.*ai.*musician.*album.*guitar',
    r'rolling.*stones.*ai.*music.*video',
    r'ai.*economy.*crash.*mounting.*chip.*costs',
    r'researchers.*let.*run.*simulated.*society.*claude.*safest.*grok.*extinct',
    r'poll.*shows.*majority.*think.*regulation.*bipartisan',
    r'x.*reportedly.*using.*sakana.*ai.*automatically.*generate',
    r'anthropic.*launches.*cowork.*claude.*desktop.*agent',
    r'railway.*secures.*100.*million.*aws.*cloud',
    r'nous.*research.*nouscoder.*14b.*coding.*model',
    r'ai.*agents.*era.*rebuild.*startups.*agent.*ngaco',
    r'mistral.*ai.*vibe.*industrial.*ai.*datacenter.*sendiri',
    r'nist.*expands.*ai.*consortium.*calls.*members',
    r'new.*protein.*folding.*ai.*predict.*1b.*proteins',
    r'anthropic.*cowork.*launched',
    r'spotify.*ai.*remix',
    r'elon.*musk.*china.*ai.*race.*pandas',
    r'china.*human.*robot.*konka.*manufacturing',
    r'japan.*humanoid.*robot.*trade.*show',
    r'gatsby.*robot.*humanoid.*bersihin.*apartemen',
    r'wix.*phk.*ribuan.*due.*ai',
    r'robot.*humanoid.*gatsby.*apartemen.*amerika',
    r'nvidia.*n1x.*arm.*windows.*pc.*computex',
    r'connecticut.*teken.*uu.*ai.*pekerja',
    r'illinois.*ai.*safety.*bill.*regulasi',
    r'colorado.*governor.*signs.*regulation.*chatbots.*minors',
    r'deepmind.*ceo.*warns.*species.*transition',
    r'presidential.*candidates.*ai.*agenda',
    r'google.*ai.*overview.*ai.*answers.*news',
    r'waymo.*ojai.*china.*robotaxi.*riders',
    r'sesame.*conversational.*ai.*ios.*app',
    r'siri.*apple.*plans.*chatgpt',
    r'groq.*chip.*650m.*funding.*nvidia',
    r'microsoft.*releases.*new.*coding.*model',
    r'autonomous.*vehicle.*registration.*texas.*waymo.*tesla',
    r'figure.*ai.*jcp.*penney.*humanoid.*robot.*retail.*job',
    r'chatgpt.*ai.*voice.*mode.*free',
    r'openai.*mlc.*mq.*leadership',
    r'spotify.*ai.*playlist.*cover.*art',
    r'openai.*advanced.*voice.*mode.*web',
    r'colorado.*regulations.*chatbot.*minors.*ai',
    r'musk.*ai.*tweet.*truth.*checking.*fact',
    r'cloudflare.*ai.*training.*data.*cleaning.*startup',
    r'apple.*ai.*data.*center.*server.*chip',
    r'japan.*robot.*trade.*show.*tokyo.*humanoid',
    r'anthropic.*trillion.*valuation.*funding.*round',
    r'trump.*loses.*control.*ai.*regulation.*illinois.*law',
    r'figure.*ai.*humanoid.*robot.*warehouse.*package',
    r'star.*wars.*rogue.*one.*gareth.*edwards.*ai.*film',
    r'spotify.*defends.*moving.*music.*better.*than.*slop',
    r'spotify.*ai.*remix.*defends',
    r'openai.*internally.*solving.*year.*old.*math.*problem',
    r'google.*launching.*personal.*agent.*ai.*gemini.*spark',
    r'x.*grok.*windows.*app.*available',
    r'openai.*canvas.*web.*code.*collaboration.*launched',
    r'microsoft.*copilot.*health.*announced.*healthcare',
    r'anthropic.*cowork.*claude.*desktop.*file.*agent',
    r'meta.*ai.*pendant.*smart.*glasses.*wearables',
    r'google.*ai.*overview.*ai.*answers.*news.*publishers',
    r'presidential.*candidates.*ai.*agenda.*2028',
    r'spotify.*ceo.*ai.*music.*defense.*press',
    r'openai.*chatgpt.*voice.*mode.*free.*all.*user',
    r'openai.*mlc.*leadership.*executive',
    r'openai.*advanced.*voice.*mode.*web.*version',
    r'anthropic.*google.*200.*billion.*chip.*cloud.*deal',
    r'anthropic.*reportedly.*agree.*pay.*google.*billion',
    r'pope.*encyclical.*ai.*dignity.*anthropic.*olah',
    r'opportunity.*humanoid.*robot.*ev.*china.*ai.*panda',
    r'ukraine.*ai.*drone.*navigation.*russia.*startup',
    r'anthropic.*acquired.*rockset.*acquired',
    r'openai.*luncurkan.*rosalind.*biodefense.*model.*biologi',
    r'softbank.*siapkan.*ipo.*spin.*robotika.*roze',
    r'chip.*china.*sembilan.*ai.*chip.*government.*certified',
    r'spacex.*data.*center.*ai.*satellite',
    r'solomon.*islands.*ai.*snake.*robot.*palmoil',
    r'auto.*tts.*research.*paper.*code',
    r'openai.*gpt.*latest.*model.*announced',
    r'deepseek.*v4.*model.*preview.*released',
    r'pope.*ai.*encyclical.*safety',
    r'x.*grok.*ai.*image.*generation',
    r'amazon.*mgm.*ai.*generated.*animated.*shows.*creator.*revolt',
    r'new.*hampshire.*ai.*bill.*signed.*puppet',
    r'figure.*ai.*job.*jcpenney.*humanoid',
}

# Filter
filtered = []
removed_keywords = 0
removed_not_quality = 0

for c in candidates:
    title_lower = c['title'].lower()
    domain = c['domain']
    
    # Must be from quality domain or have unique content
    is_quality = domain in QUALITY_DOMAINS or any(d in domain for d in ['techcrunch', 'arstechnica', 'theverge', 'wired', 'cnbc', 'bloomberg', 'reuters', 'bbc', 'nytimes', 'wsj', 'fortune', 'forbes', 'engadget', 'venturebeat', 'theinformation', 'guardian', 'npr', 'axios', 'nbcnews', 'hollywoodreporter', 'variety', 'deadline', 'rollingstone', 'nature', 'scientificamerican', 'nikkei', 'ft.com', 'economist', 'anthropic', 'openai', 'blog.google', 'mashable', 'gizmodo', 'tomshardware', 'theregister', 'zdnet', 'cnet', 'techradar', 'digitaltrends', 'pcmag', 'interestingengineering', 'livescience', 'ieee.org', 'androidpolice', 'theinformation', 'thehill', 'politico', 'apnews', 'cbsnews', 'abcnews', 'latimes', 'indiewire', 'newyorker', 'atlantic', 'washingtonpost', 'time', 'newsweek', 'fastcompany', 'inc.com', 'qz.com', 'koreaherald', 'techtimes', 'marketwatch', 'blogs.nvidia.com', 'cloudflare.com/blog', 'space.com', 'scmp.com', 'yonhap'])
    
    if not is_quality:
        removed_not_quality += 1
        continue
    
    # Check blacklist
    blacklisted = False
    for pattern in BLACKLIST_PATTERNS:
        if re.search(pattern, title_lower):
            blacklisted = True
            removed_keywords += 1
            break
    
    if blacklisted:
        continue
    
    filtered.append(c)

print(f"Removed (not quality source): {removed_not_quality}")
print(f"Removed (blacklisted): {removed_keywords}")
print(f"Remaining candidates: {len(filtered)}")
print()

for i, c in enumerate(filtered, 1):
    print(f"{i}. [{c['domain']}] {c['title'][:120]}")

with open('filtered_candidates.json', 'w') as f:
    json.dump(filtered, f, indent=2, ensure_ascii=False)
